services:
  # TaskPilot FastAPI Web Service
  - type: web
    name: taskpilot-api
    runtime: docker
    repo: https://github.com/RoeeShlosberg/TaskPilot
    branch: main
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    
    # Environment variables
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./data/taskpilot.db
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: AI_PROVIDER
        value: openrouter
      - key: AI_API_KEY
        fromDatabase:
          name: taskpilot-secrets
          property: ai_api_key
      - key: REDIS_HOST
        fromService:
          type: redis
          name: taskpilot-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: taskpilot-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: taskpilot-redis
          property: password
      - key: REDIS_DB
        value: 0
      - key: APP_NAME
        value: TaskPilot
      - key: DEBUG
        value: false
        
    # Health check
    healthCheckPath: /health
    
    # Scaling and resources
    numInstances: 1
    plan: starter
    
    # Persistent disk for SQLite database
    disk:
      name: taskpilot-data
      mountPath: /app/data
      sizeGB: 1

  # TaskPilot React Client
  - type: web
    name: taskpilot-client
    runtime: docker
    repo: https://github.com/RoeeShlosberg/TaskPilot
    branch: main
    dockerfilePath: ./docker/client.DockerFile
    dockerContext: .
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        fromService:
          type: web
          name: taskpilot-api
          envVarKey: RENDER_EXTERNAL_URL
    
    # Health check
    healthCheckPath: /
    
    # Scaling and resources
    numInstances: 1
    plan: starter

  # Redis Cache Service
  - type: redis
    name: taskpilot-redis
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: allkeys-lru

# Databases (for storing secrets)
databases:
  - name: taskpilot-secrets
    plan: starter
    databaseName: taskpilot_secrets
