services:
  # TaskPilot FastAPI Web Service
  - type: web
    name: taskpilot-api
    runtime: docker
    repo: https://github.com/RoeeShlosberg/TaskPilot
    branch: main
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    
    # Environment variables
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./data/taskpilot.db
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: AI_PROVIDER
        value: openrouter
      - key: AI_API_KEY
        value: ""  # You'll need to set this manually in Render dashboard
      - key: REDIS_HOST
        value: ""  # Redis disabled for free tier
      - key: REDIS_PORT
        value: 0  # Redis disabled for free tier
      - key: REDIS_PASSWORD
        value: ""  # Redis disabled for free tier
      - key: REDIS_DB
        value: 0
      - key: APP_NAME
        value: TaskPilot
      - key: DEBUG
        value: false
        
    # Health check
    healthCheckPath: /health
    
    # Scaling and resources
    numInstances: 1
    plan: free
    
    # Note: Free plan doesn't support persistent disks
    # SQLite database will be in-memory only

  # TaskPilot React Client
  - type: web
    name: taskpilot-client
    runtime: docker
    repo: https://github.com/RoeeShlosberg/TaskPilot
    branch: main
    dockerfilePath: ./docker/client.DockerFile
    dockerContext: .
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        fromService:
          type: web
          name: taskpilot-api
          envVarKey: RENDER_EXTERNAL_URL
    
    # Health check
    healthCheckPath: /
    
    # Scaling and resources
    numInstances: 1
    plan: free

  # Redis Cache Service (commented out - requires payment)
  # - type: redis
  #   name: taskpilot-redis
  #   ipAllowList: []
  #   plan: starter
  #   maxmemoryPolicy: allkeys-lru

# Databases (commented out - requires payment)
# databases:
#   - name: taskpilot-secrets
#     plan: starter
#     databaseName: taskpilot_secrets